variables:
  ProjectName: "webpack_study"
  BuildResult: buildResult.txt
  BranchLimit: /^\d{8}$/

stages:
  - build
  - deploy
  - publish

cache:
  key: defaultCache
  paths:
    - node_modules/
    - package-lock.json

before_script:
  - echo "初始化环境 更新依赖和配置..."
  - npm install
  - echo "环境初始化完成!"
  - echo "依赖和配置更新完成!"

Build_Test_Job:
  stage: build
  when: manual
  only:
    - $BranchLimit
  script:
    - echo "开始执行构建测试环境Web脚本..."
    - npm run stage > $BuildResult
    - if [ -d /opt/web/build ]; then rm -rf /opt/web/build > $BuildResult; fi
    - mv build /opt/web/ > $BuildResult
    - echo "测试环境Web打包并部署完成! 可以访问端口8087查看"
  artifacts:
    paths:
      - $BuildResult

DEPLOY_Test_Job:
  stage: deploy
  when: manual
  only:
    - $BranchLimit
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

PUBLISH_Test_Job:
  stage: publish
  when: manual
  only:
    - $BranchLimit
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."
